// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTYUf6BUJS17vj7rztHKx-NZoqfW_aUBc',
    appId: '1:579942784197:web:7433be36479b62975c64ac',
    messagingSenderId: '579942784197',
    projectId: 'closed-testing-2f318',
    authDomain: 'closed-testing-2f318.firebaseapp.com',
    storageBucket: 'closed-testing-2f318.firebasestorage.app',
    measurementId: 'G-5V2QC6W4YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2n6WgOj_APoclFVM-E2DeQTJDFDNoNzY',
    appId: '1:579942784197:android:6c0a4dd26982173c5c64ac',
    messagingSenderId: '579942784197',
    projectId: 'closed-testing-2f318',
    storageBucket: 'closed-testing-2f318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHblKzY1bSYVTwKGUo9Vt6bPk3t4BBIw',
    appId: '1:579942784197:ios:4e9fe7b2a99db4355c64ac',
    messagingSenderId: '579942784197',
    projectId: 'closed-testing-2f318',
    storageBucket: 'closed-testing-2f318.firebasestorage.app',
    iosClientId: '579942784197-lo8u96ermtookepn9uv5r5q8tatlbo2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.closedTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSHblKzY1bSYVTwKGUo9Vt6bPk3t4BBIw',
    appId: '1:579942784197:ios:4e9fe7b2a99db4355c64ac',
    messagingSenderId: '579942784197',
    projectId: 'closed-testing-2f318',
    storageBucket: 'closed-testing-2f318.firebasestorage.app',
    iosClientId: '579942784197-lo8u96ermtookepn9uv5r5q8tatlbo2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.closedTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTYUf6BUJS17vj7rztHKx-NZoqfW_aUBc',
    appId: '1:579942784197:web:bba49e8f40f9687c5c64ac',
    messagingSenderId: '579942784197',
    projectId: 'closed-testing-2f318',
    authDomain: 'closed-testing-2f318.firebaseapp.com',
    storageBucket: 'closed-testing-2f318.firebasestorage.app',
    measurementId: 'G-G9BZKCVFG8',
  );

}